server:
  port: 8082

  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/eternity?currentSchema=student
    username: postgres
    password: eternity123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      indent_output: true